server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  config:
    import: optional:file:.env

  graphql:
    path: /graphql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}

  datasource:
    master:
      url: ${DB_MASTER_URL}
      username: ${DB_MASTER_USERNAME}
      password: ${DB_MASTER_PASSWORD}

    slave:
      url: ${DB_SLAVE_URL}
      username: ${DB_SLAVE_USERNAME}
      password: ${DB_SLAVE_PASSWORD}

    hikari:
      max-lifetime: ${DB_MAX_LIFETIME}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      keepalive-time: ${DB_KEEPALIVE_TIME}
      validation-timeout: ${DB_VALIDATION_TIMEOUT}
      connection-timeout: ${DB_CONNECTION_TIMEOUT}
      maximum-pool-size: ${DB_MAX_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate.hibernate.format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    database: ${NEO4J_DATABASE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
    port: ${JOBRUNR_DASHBOARD_PORT}


idp:
  url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.xxxx.backend_mvc: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE