"""
Generate Requirements Traceability Matrix Excel file for TaskFlow project.

Source: CodeGraph analysis of /be/nckh (Spring Boot DDD) and /fe_web/react-web (React 18 + Redux Toolkit + Playwright).
Convention:
  - US-[MODULE]-NNN
  - AC-[MODULE]-NNN
  - FC-[MODULE]-NNN
  - NFC-[CATEGORY]-NNN
  - TC-[MODULE]-NNN
Evidence tags: EXPLICIT (trực tiếp trong code/doc) | INFERRED (suy ra từ impl) | NEEDS_REVIEW (chưa đủ bằng chứng)
"""

import os
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation

OUTPUT_PATH = os.path.join(os.getcwd(), "requirements_traceability_matrix.xlsx")

# ---------- styles ----------
HEADER_FILL = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
THIN = Side(border_style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
WRAP = Alignment(wrap_text=True, vertical="top")
CENTER = Alignment(horizontal="center", vertical="center")

EVIDENCE_FILLS = {
    "EXPLICIT": PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid"),  # green
    "INFERRED": PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid"),  # amber
    "NEEDS_REVIEW": PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid"),  # red
}


def fill_evidence(cell, value: str):
    cell.fill = EVIDENCE_FILLS.get(value, PatternFill(fill_type=None))


def style_header(ws, num_cols: int):
    for col in range(1, num_cols + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = CENTER
        cell.border = BORDER
    ws.freeze_panes = "A2"


def autosize(ws, widths: dict):
    for col_idx, width in widths.items():
        ws.column_dimensions[get_column_letter(col_idx)].width = width


def write_table(ws, headers: list, rows: list, widths: dict):
    ws.append(headers)
    style_header(ws, len(headers))
    for r in rows:
        ws.append(r)
    last_row = ws.max_row
    last_col = ws.max_column
    for row in ws.iter_rows(min_row=1, max_row=last_row, min_col=1, max_col=last_col):
        for cell in row:
            cell.border = BORDER
            cell.alignment = WRAP
    # Apply evidence fills when applicable columns exist
    for col_idx, header in enumerate(headers, start=1):
        if header == "Evidence_Type":
            for r in range(2, last_row + 1):
                v = ws.cell(row=r, column=col_idx).value
                if v in EVIDENCE_FILLS:
                    fill_evidence(ws.cell(row=r, column=col_idx), v)
        if header == "Status":
            for r in range(2, last_row + 1):
                v = ws.cell(row=r, column=col_idx).value
                if v == "PASS":
                    fill_evidence(ws.cell(row=r, column=col_idx), "EXPLICIT")
                elif v == "FAIL":
                    fill_evidence(ws.cell(row=r, column=col_idx), "NEEDS_REVIEW")
                elif v in ("PROPOSED", "PENDING"):
                    fill_evidence(ws.cell(row=r, column=col_idx), "INFERRED")
        if header == "Coverage_Status":
            for r in range(2, last_row + 1):
                v = ws.cell(row=r, column=col_idx).value
                if v == "COVERED":
                    fill_evidence(ws.cell(row=r, column=col_idx), "EXPLICIT")
                elif v == "PARTIAL":
                    fill_evidence(ws.cell(row=r, column=col_idx), "INFERRED")
                elif v in ("MISSING", "BLOCKED"):
                    fill_evidence(ws.cell(row=r, column=col_idx), "NEEDS_REVIEW")
    # autofilter
    ws.auto_filter.ref = f"A1:{get_column_letter(last_col)}{last_row}"
    autosize(ws, widths)


def add_dropdowns(ws, col_letter: str, options: list, last_row: int):
    dv = DataValidation(type="list", formula1='"' + ",".join(options) + '"', allow_blank=True)
    dv.add(f"{col_letter}2:{col_letter}{last_row}")
    ws.add_data_validation(dv)


# ---------- DATA ----------
# Common reference values
PROJECT_NAME = "TaskFlow"
SRC_BE = "be/nckh"
SRC_FE = "fe_web/react-web"

# ===== User Stories =====
user_stories = [
    # AUTH
    ("US-AUTH-001", "Authentication", "Guest / End User",
     "As a guest, I want to log in with username and password, so that I can access my workspace data securely.",
     "Enable secure access to workspace using existing Keycloak account.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_FE}/src/pages/auth/LoginPage.tsx", "LoginPage.handleSubmit",
     "Logs in via Keycloak password grant using /realms/nckh/protocol/openid-connect/token"),
    ("US-AUTH-002", "Authentication", "Guest / End User",
     "As a guest, I want to register a new account, so that I can use TaskFlow.",
     "Onboard new users through Keycloak Admin API.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_FE}/src/pages/auth/RegisterPage.tsx", "RegisterPage.handleSubmit",
     "4-step wizard; registers via /auth/register -> IdentityServiceImpl.createUser"),
    ("US-AUTH-003", "Authentication", "End User",
     "As an end user, I want my access token to be refreshed automatically, so that I do not get logged out during active use.",
     "Avoid forcing users to re-authenticate when access token expires.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_FE}/src/services/api.ts", "api.interceptors.response",
     "On 401, calls refresh_token grant; queues other requests until done"),
    ("US-AUTH-004", "Authentication", "End User",
     "As an end user, I want to log in with Google or GitHub, so that I can sign in faster.",
     "Reduce friction for SSO users.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_FE}/src/services/authService.ts", "authService.loginWithGoogle/loginWithGithub",
     "Browser redirect to Keycloak with kc_idp_hint; state CSRF token persisted in sessionStorage"),
    ("US-AUTH-005", "Authentication", "End User",
     "As an end user, I want my JWT to be validated on every backend request, so that no one else can impersonate me.",
     "Centralize authentication on backend; block unauthorized traffic.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/nckh-infrastructure/.../SecurityConfig.java", "SecurityConfig.filterChain",
     "OAuth2 Resource Server JWT; PUBLIC_ENDPOINTS only ['/register','/error']"),
    ("US-AUTH-006", "Authentication", "End User",
     "As an end user, I want my expired/invalid token to receive a 401 with a clear JSON message, so that the UI can react.",
     "Consistent error contract via GlobalExceptionHandler.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/nckh-controller/.../GlobalExceptionHandler.java", "GlobalExceptionHandler",
     "Returns ApiResponse with code 9999 / 1006 / 1007"),
    # PROFILE
    ("US-PROFILE-001", "Profile", "End User",
     "As an end user, I want to view my profile, so that I can confirm my account information.",
     "Show profile read view.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_FE}/src/pages/Profile.tsx", "Profile component",
     "Renders name/email/bio/location/website; tabs activity/workspaces/teams"),
    ("US-PROFILE-002", "Profile", "End User",
     "As an end user, I want to fetch the list of profiles, so that we can resolve mentions and members.",
     "Backend lookup of all profiles.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../ProfileController.java", "ProfileController.getAllProfiles",
     "GET /profiles returns ApiResponse<List<ProfileResponse>>"),
    # WORKSPACE
    ("US-WORKSPACE-001", "Workspace", "End User",
     "As an end user, I want to create a workspace, so that I can organize my projects.",
     "Allow any authenticated user to create a workspace; owner becomes ADMIN.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "createWorkspace",
     "Seeds 3 WorkspaceRoles (ADMIN/MEMBER/VIEWER) and assigns creator as ADMIN; sets up a Backlog"),
    ("US-WORKSPACE-002", "Workspace", "Workspace Member",
     "As a member, I want to see all my workspaces, so that I can switch between projects quickly.",
     "List workspaces where current user is a member.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "getAllWorkspaces",
     "Returns workspaces with ownerId resolved to first ADMIN"),
    ("US-WORKSPACE-003", "Workspace", "Workspace Admin",
     "As an admin, I want to update workspace name/type/access, so that I can keep information accurate.",
     "Admin can edit workspace metadata.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceController.java", "WorkspaceController.updateWorkspace",
     "PUT /workspace/{id}; requires WORKSPACE_ADMINISTER"),
    ("US-WORKSPACE-004", "Workspace", "Workspace Admin",
     "As an admin, I want to delete a workspace, so that obsolete projects can be removed.",
     "Admin can delete a workspace (cascade).", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceController.java", "WorkspaceController.deleteWorkspace",
     "DELETE /workspace/{id}; requires WORKSPACE_DELETE"),
    ("US-WORKSPACE-005", "Workspace", "Workspace Admin",
     "As an admin, I want to trigger graph rebuild, so that the similarity graph reflects new stories.",
     "Manual graph regeneration trigger.", "Low", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceController.java", "WorkspaceController.rebuildGraph",
     "POST /workspace/{id}/rebuild-graph -> GraphEventPort.sendRebuildEvent"),
    # MEMBER
    ("US-MEMBER-001", "Workspace Member", "Workspace Member",
     "As a member, I want to view the list of other members and their roles, so that I know who is in the project.",
     "List members in the workspace sidebar / members page.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceController.java", "getMembers",
     "GET /workspace/{id}/members; requires MEMBER_VIEW"),
    # INVITATION
    ("US-INVITE-001", "Invitation", "Workspace Admin",
     "As an admin, I want to invite a user by email, so that they can join the workspace.",
     "Send invitation email + in-app notification.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "inviteMemberToWorkspace",
     "Creates WorkspaceInvitation with 3-day expiry, sends email afterCommit, notifies invitee"),
    ("US-INVITE-002", "Invitation", "Invitee",
     "As an invitee, I want to accept or deny an invitation, so that I can choose whether to join.",
     "Invitee controls join decision.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../InvitationController.java", "accept/deny",
     "POST /invitations/{id}/accept | /deny; checks expiry + ownership"),
    ("US-INVITE-003", "Invitation", "End User",
     "As a user, I want to see my pending invitations, so that I do not miss them.",
     "Surface pending invites to UI.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../InvitationController.java", "myPendingInvitations",
     "GET /invitations/pending"),
    # RBAC
    ("US-RBAC-001", "RBAC", "Workspace Admin",
     "As an admin, I want to view the permission matrix for my workspace, so that I can audit role capabilities.",
     "Jira-style RBAC visibility.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceRoleController.java", "getPermissionMatrix",
     "Returns role -> set of Permission; ADMIN/MEMBER/VIEWER seeded"),
    ("US-RBAC-002", "RBAC", "Workspace Admin",
     "As an admin, I want to change permissions of a role, so that I can fine-tune access.",
     "Edit permission set for a non-admin role.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceRoleAppServiceImpl.java", "updateRolePermissions",
     "Forbids removing WORKSPACE_ADMINISTER from ADMIN role"),
    ("US-RBAC-003", "RBAC", "Workspace Admin",
     "As an admin, I want to change a member's role, so that I can promote or demote them.",
     "Switch a member between MEMBER/VIEWER; protect last admin.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceRoleAppServiceImpl.java", "changeMemberRole",
     "Throws CANNOT_DEMOTE_LAST_ADMIN if it would remove the last admin"),
    ("US-RBAC-004", "RBAC", "Workspace Admin",
     "As an admin, I want to grant per-resource permissions, so that I can override defaults for specific sprints/stories.",
     "ACL-style ResourceGrant overrides.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceRoleController.java", "createGrant/listGrants/deleteGrant",
     "POST/GET/DELETE /workspace/{id}/grants with resourceType/resourceId filters"),
    # SPRINT
    ("US-SPRINT-001", "Sprint", "Workspace Member",
     "As a member, I want to create a sprint, so that I can plan work for the next iteration.",
     "Sprint lifecycle: ToDo -> InProgress -> Done.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SprintAppServiceImpl.java", "createSprint",
     "POST /sprints/workspace/{id} -> SprintStatus.ToDo"),
    ("US-SPRINT-002", "Sprint", "Workspace Member",
     "As a member, I want to add stories to a sprint, so that I can scope the work.",
     "Move backlog stories into a sprint.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SprintController.java", "addUserStory(ies)ToSprint",
     "POST /sprints/{id}/user-stories and /sprints/{id}/user-stories/{usId}"),
    ("US-SPRINT-003", "Sprint", "Workspace Member",
     "As a member, I want to start a sprint, so that the team commits to the work.",
     "Only one active sprint per workspace.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SprintAppServiceImpl.java", "startSprint",
     "Throws SPRINT_ALREADY_ACTIVE if another sprint is InProgress"),
    ("US-SPRINT-004", "Sprint", "Workspace Member",
     "As a member, I want to complete a sprint, so that unfinished work goes back to the backlog.",
     "Stories not Done move back to Backlog with status ToDo.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SprintAppServiceImpl.java", "completeSprint",
     "Resets story status, clears sprint, publishes USER_STORY_MOVED events afterCommit"),
    ("US-SPRINT-005", "Sprint", "Workspace Member",
     "As a member, I want to remove a story from a sprint, so that I can correct the plan.",
     "Story returns to backlog.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SprintController.java", "removeUserStoryFromSprint",
     "DELETE /sprints/user-stories/{usId}"),
    # USER STORY
    ("US-US-001", "User Story", "Workspace Member",
     "As a member, I want to create user stories, so that I can capture requirements.",
     "Bulk create stories in a workspace backlog.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../UserStoryController.java", "createUserStory",
     "POST /user-stories/workspace/{id} takes List<UserStoryCreateRequest>"),
    ("US-US-002", "User Story", "Workspace Member",
     "As a member, I want to view the backlog, so that I can see unscheduled stories.",
     "List stories with sprint_id IS NULL.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../UserStoryController.java", "getBacklog",
     "GET /user-stories/workspace/{id}/backlog"),
    ("US-US-003", "User Story", "Workspace Member",
     "As a member, I want to change a story status, so that I can show progress on the kanban board.",
     "Status transitions only within an InProgress sprint.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../UserStoryAppServiceImpl.java", "updateStatus",
     "Rejects USER_STORY_NOT_IN_SPRINT and SPRINT_NOT_ACTIVE"),
    ("US-US-004", "User Story", "Workspace Member",
     "As a member, I want to delete a user story, so that I can clean up the backlog.",
     "Soft permission gate by ISSUE_DELETE.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../UserStoryController.java", "delete",
     "DELETE /user-stories/{id}"),
    # NOTIFICATION
    ("US-NOTIF-001", "Notification", "End User",
     "As a user, I want to see unread notifications, so that I know what needs my attention.",
     "List unread notifications newest first.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../NotificationController.java", "getUnread",
     "GET /notifications/unread"),
    ("US-NOTIF-002", "Notification", "End User",
     "As a user, I want to mark a notification as read, so that I can track what I have handled.",
     "Single and bulk mark-as-read.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../NotificationController.java", "markAsRead/markAllAsRead",
     "PATCH /notifications/{id}/read and /read-all"),
    ("US-NOTIF-003", "Notification", "End User",
     "As a user, I want realtime push of new notifications, so that my UI updates without refresh.",
     "WebSocket push if user is online.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../NotificationAppServiceImpl.java", "notifyUser",
     "Calls RealtimeNotificationPort.send if user is online"),
    # GRAPH
    ("US-GRAPH-001", "Graph", "Workspace Member",
     "As a member, I want to query the workspace similarity graph, so that I can visualise relationships.",
     "GraphQL query with filters: source, score, confidence.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../GraphQueryResolver.java", "workspaceGraph",
     "GraphQL @QueryMapping; valid source REALTIME|BATCH else IllegalArgumentException"),
    ("US-GRAPH-002", "Graph", "Workspace Member",
     "As a member, I want to filter graph by sprint/backlog, so that I can scope analysis.",
     "Optional sprintId/backlogId filter.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../GraphServiceImpl.java", "getWorkspaceGraph",
     "Cypher filter on sprint_id/backlog_id where applicable"),
    # OBSERVABILITY
    ("US-OBS-001", "Observability", "Operator",
     "As an operator, I want Spring Security logs at DEBUG, so that I can troubleshoot auth issues.",
     "Configured DEBUG logging for security + web.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "logging.level",
     "DEBUG for spring-security, spring-web, com.xxxx.backend_mvc"),
    ("US-OBS-002", "Observability", "Operator",
     "As an operator, I want a JobRunr dashboard, so that I can inspect background jobs.",
     "Background job server + dashboard enabled.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "jobrunr.*",
     "background-job-server.enabled=true; dashboard enabled on JOBRUNR_DASHBOARD_PORT"),
    # CROSS
    ("US-CROSS-001", "Cross-cutting", "Operator",
     "As an operator, I want CORS preflight to pass for all origins, so that the SPA can call the API.",
     "Permissive CORS configuration for dev.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../SecurityConfig.java", "corsConfigurationSource",
     "allowedOriginPatterns='*'; allowedMethods='*'"),
    ("US-CROSS-002", "Cross-cutting", "Operator",
     "As an operator, I want API-key fallback for service-to-service calls, so that internal jobs can call the API.",
     "Filter-based x-api-key check.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../ApiKeyFilter.java", "ApiKeyFilter",
     "Reads X-API-Key header and authenticates via API key"),
    ("US-CROSS-003", "Cross-cutting", "Operator",
     "As an operator, I want writes to hit master and reads to hit slave DB, so that read load is balanced.",
     "RoutingDataSource + @ReadOnly annotation.", "High", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../DataSourceConfig.java", "DataSourceConfig + @ReadOnly",
     "Master/Slave data sources configured; ReadOnly switches to slave"),
    ("US-CROSS-004", "Cross-cutting", "Operator",
     "As an operator, I want email to be sent asynchronously after transaction commit, so that users do not wait on SMTP.",
     "TransactionSynchronizationManager.afterCommit hooks.", "Medium", "Implemented",
     "EXPLICIT",
     f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "TransactionSynchronizationManager.registerSynchronization",
     "Invitation email is sent after the DB commit"),
]

# ===== Acceptance Criteria =====
acceptance_criteria = [
    # US-AUTH-001
    ("AC-AUTH-001", "US-AUTH-001", "Successful login",
     "User is authenticated and has an access token in localStorage",
     "User submits valid username/password",
     "User is redirected to '/' and Redux state holds tokens"),
    ("AC-AUTH-002", "US-AUTH-001", "Failed login",
     "Login form is shown with the error message from Keycloak",
     "User submits invalid credentials",
     "Axios error is shown in the email field; no token is stored"),
    ("AC-AUTH-003", "US-AUTH-002", "Multi-step registration",
     "Wizard blocks Next until current step validates",
     "User skips a required field on a step",
     "Inline error appears and Next does not advance"),
    ("AC-AUTH-004", "US-AUTH-002", "Registration validation",
     "User must be at least 13 years old",
     "User enters a DOB that makes them under 13",
     "Inline error 'You must be at least 13 years old' is shown"),
    ("AC-AUTH-005", "US-AUTH-003", "Auto token refresh",
     "Queued requests retry with new token",
     "Expired token triggers 401 on parallel requests",
     "All queued requests succeed after refresh; user is not redirected"),
    ("AC-AUTH-006", "US-AUTH-003", "Missing refresh token",
     "User is sent to /login",
     "Access token expires and no refresh token exists",
     "localStorage cleared; window.location = '/login'"),
    ("AC-AUTH-007", "US-AUTH-004", "OAuth login",
     "Browser is redirected to Keycloak with state CSRF token",
     "User clicks 'Continue with Google/GitHub'",
     "sessionStorage holds oauth_state; redirect URL contains kc_idp_hint"),
    ("AC-AUTH-008", "US-AUTH-005", "Unauthenticated request rejected",
     "All endpoints except /register and /error require JWT",
     "Anonymous client calls /sprints",
     "Response is 401 with ApiResponse code=1006"),
    ("AC-AUTH-009", "US-AUTH-005", "Authenticated request accepted",
     "Valid JWT authorizes the request",
     "Client sends Authorization: Bearer <token>",
     "Endpoint returns 200 with ApiResponse code=1000"),
    ("AC-AUTH-010", "US-AUTH-006", "Consistent error JSON",
     "All errors return ApiResponse shape",
     "Any uncaught exception occurs",
     "Response body has {code, message} matching ErrorCode"),
    # PROFILE
    ("AC-PROFILE-001", "US-PROFILE-001", "Profile page renders",
     "User is logged in and navigates to /profile",
     "Page is rendered",
     "Name, email, bio and tabs are visible"),
    ("AC-PROFILE-002", "US-PROFILE-002", "List all profiles",
     "Caller has appropriate JWT scope",
     "GET /profiles is called",
     "ApiResponse with List<ProfileResponse>"),
    # WORKSPACE
    ("AC-WORKSPACE-001", "US-WORKSPACE-001", "Create workspace",
     "Authenticated user with valid name/type/access",
     "User POSTs /workspace",
     "Workspace, Backlog and 3 seeded roles are persisted; caller becomes ADMIN"),
    ("AC-WORKSPACE-002", "US-WORKSPACE-002", "List my workspaces",
     "Caller is a member of at least one workspace",
     "User GETs /workspace",
     "List of workspaces where caller is a member, with ownerId"),
    ("AC-WORKSPACE-003", "US-WORKSPACE-003", "Permissions required",
     "Caller lacks WORKSPACE_ADMINISTER",
     "User PUTs /workspace/{id}",
     "Error 1007 UNAUTHORIZED"),
    ("AC-WORKSPACE-004", "US-WORKSPACE-004", "Delete workspace",
     "Caller is admin",
     "User DELETEs /workspace/{id}",
     "Workspace removed; subsequent GET returns 1012"),
    ("AC-WORKSPACE-005", "US-WORKSPACE-005", "Trigger rebuild",
     "Caller is admin",
     "User POSTs /workspace/{id}/rebuild-graph",
     "GraphEventPort.sendRebuildEvent is called"),
    # MEMBER
    ("AC-MEMBER-001", "US-MEMBER-001", "View members",
     "Caller has MEMBER_VIEW",
     "GET /workspace/{id}/members",
     "List of WorkspaceMemberResponse with userId/email/role"),
    # INVITE
    ("AC-INVITE-001", "US-INVITE-001", "Send invitation",
     "Inviter has MEMBER_INVITE; invitee exists; not already a member",
     "Member POSTs /workspace/{id}/invitations",
     "WorkspaceInvitation created with 3-day expiry; in-app notification + email queued"),
    ("AC-INVITE-002", "US-INVITE-001", "Reject self-invite",
     "Inviter's email equals invitee's email",
     "User POSTs invitation to their own email",
     "Error 1016 INVALID_INVITE"),
    ("AC-INVITE-003", "US-INVITE-001", "Reject ADMIN invite",
     "Inviter tries to invite as ADMIN",
     "Request role=ADMIN",
     "Error 1032 INVALID_ROLE"),
    ("AC-INVITE-004", "US-INVITE-001", "Duplicate pending",
     "Pending invitation already exists",
     "User re-invites the same person",
     "Error 1019 INVITATION_ALREADY_SENT"),
    ("AC-INVITE-005", "US-INVITE-002", "Accept invitation",
     "Invitee is logged in; invitation is PENDING; not expired",
     "Invitee POSTs /invitations/{id}/accept",
     "WorkspaceMember added; notification sent to inviter"),
    ("AC-INVITE-006", "US-INVITE-002", "Accept wrong user",
     "Caller is not the invitee",
     "Other user POSTs accept",
     "Error 1014 NO_PERMISSION"),
    ("AC-INVITE-007", "US-INVITE-002", "Accept expired",
     "Invitation expiredAt < now",
     "Invitee accepts",
     "Error 1018 INVITE_EXPIRED"),
    ("AC-INVITE-008", "US-INVITE-002", "Deny invitation",
     "Invitee is logged in and is the invitee",
     "Invitee POSTs /invitations/{id}/deny",
     "Status -> REJECTED; inviter notified"),
    ("AC-INVITE-009", "US-INVITE-003", "List my pending",
     "Caller is authenticated",
     "User GETs /invitations/pending",
     "List of pending invitations for the caller"),
    # RBAC
    ("AC-RBAC-001", "US-RBAC-001", "Get permission matrix",
     "Caller has WORKSPACE_BROWSE",
     "GET /workspace/{id}/permission-matrix",
     "List of RolePermissionMatrixResponse with role + permissions set"),
    ("AC-RBAC-002", "US-RBAC-002", "Cannot strip admin flag",
     "Caller tries to remove WORKSPACE_ADMINISTER from ADMIN role",
     "PUT /workspace/{id}/roles/ADMIN/permissions without admin flag",
     "Service re-adds WORKSPACE_ADMINISTER before saving"),
    ("AC-RBAC-003", "US-RBAC-003", "Last admin protection",
     "Caller would become the only non-admin",
     "Demote the only remaining admin",
     "Error 1031 CANNOT_DEMOTE_LAST_ADMIN"),
    ("AC-RBAC-004", "US-RBAC-004", "Resource grant CRUD",
     "Caller has WORKSPACE_ADMINISTER",
     "POST/GET/DELETE /workspace/{id}/grants",
     "Grant created, listed (optionally filtered), deleted"),
    # SPRINT
    ("AC-SPRINT-001", "US-SPRINT-001", "Create sprint",
     "Caller has SPRINT_CREATE; workspace exists",
     "POST /sprints/workspace/{id}",
     "Sprint persisted with status=ToDo"),
    ("AC-SPRINT-002", "US-SPRINT-002", "Add story to sprint",
     "Sprint is in ToDo; user stories belong to same workspace",
     "POST /sprints/{id}/user-stories/{usId}",
     "Story.sprint set, Story.backlog cleared"),
    ("AC-SPRINT-003", "US-SPRINT-002", "Cross-workspace story rejected",
     "Story belongs to a different workspace",
     "POST add-story",
     "Error 1024 INVALID_WORKSPACE"),
    ("AC-SPRINT-004", "US-SPRINT-002", "Missing story rejected",
     "Some story IDs do not exist",
     "POST /sprints/{id}/user-stories",
     "Error 1023 USER_STORY_NOT_FOUND"),
    ("AC-SPRINT-005", "US-SPRINT-003", "Start sprint happy path",
     "Caller has SPRINT_MANAGE; sprint is ToDo; no active sprint",
     "POST /sprints/{id}/start",
     "Status -> InProgress; USER_STORY_MOVED events published afterCommit"),
    ("AC-SPRINT-006", "US-SPRINT-003", "Sprint already active",
     "Another sprint is InProgress",
     "POST start on another sprint",
     "Error 1022 SPRINT_ALREADY_ACTIVE"),
    ("AC-SPRINT-007", "US-SPRINT-003", "Invalid state transition",
     "Sprint is Done",
     "POST start",
     "Error 1021 SPRINT_INVALID_STATE"),
    ("AC-SPRINT-008", "US-SPRINT-004", "Complete sprint",
     "Sprint is InProgress",
     "POST /sprints/{id}/complete",
     "Status -> Done; unfinished stories move back to Backlog with status ToDo"),
    ("AC-SPRINT-009", "US-SPRINT-005", "Remove story",
     "Caller has SPRINT_EDIT",
     "DELETE /sprints/user-stories/{usId}",
     "Story.sprint cleared"),
    # USER STORY
    ("AC-US-001", "US-US-001", "Create stories",
     "Caller has ISSUE_CREATE; workspace exists",
     "POST /user-stories/workspace/{id} with array",
     "Stories persisted with default status=ToDo; events published afterCommit"),
    ("AC-US-002", "US-US-002", "View backlog",
     "Caller has ISSUE_VIEW",
     "GET /user-stories/workspace/{id}/backlog",
     "List of stories where sprint is null"),
    ("AC-US-003", "US-US-003", "Update status happy path",
     "Caller has ISSUE_TRANSITION; story is in InProgress sprint",
     "PUT /user-stories/{id}/status with new status",
     "Story.status updated"),
    ("AC-US-004", "US-US-003", "Story not in sprint",
     "Story.sprint is null",
     "PUT status",
     "Error 1026 USER_STORY_NOT_IN_SPRINT"),
    ("AC-US-005", "US-US-003", "Sprint not active",
     "Story is in a sprint with status != InProgress",
     "PUT status",
     "Error 1027 SPRINT_NOT_ACTIVE"),
    ("AC-US-006", "US-US-004", "Delete story",
     "Caller has ISSUE_DELETE",
     "DELETE /user-stories/{id}",
     "Story removed"),
    # NOTIFICATION
    ("AC-NOTIF-001", "US-NOTIF-001", "Unread list",
     "Caller is authenticated",
     "GET /notifications/unread",
     "List of unread notifications newest first"),
    ("AC-NOTIF-002", "US-NOTIF-002", "Mark as read",
     "Notification belongs to caller",
     "PATCH /notifications/{id}/read",
     "Notification.read = true"),
    ("AC-NOTIF-003", "US-NOTIF-002", "Mark all as read",
     "Caller has at least one unread",
     "PATCH /notifications/read-all",
     "All caller's notifications.read = true"),
    ("AC-NOTIF-004", "US-NOTIF-003", "Realtime push",
     "Caller is online",
     "Server calls NotificationAppService.notifyUser",
     "RealtimeNotificationPort.send is invoked; DB row also persisted"),
    # GRAPH
    ("AC-GRAPH-001", "US-GRAPH-001", "Query workspace graph",
     "Caller has WORKSPACE_BROWSE",
     "POST /graphql with workspaceGraph",
     "GraphResponse with nodes and edges"),
    ("AC-GRAPH-002", "US-GRAPH-001", "Invalid source rejected",
     "Caller passes source=INVALID",
     "workspaceGraph call",
     "IllegalArgumentException"),
    ("AC-GRAPH-003", "US-GRAPH-002", "Filter by sprint",
     "Caller provides sprintId",
     "workspaceGraph query",
     "Only edges scoped to that sprint are returned"),
    # OBSERVABILITY
    ("AC-OBS-001", "US-OBS-001", "Security DEBUG logs",
     "Spring starts",
     "Application logs at DEBUG for org.springframework.security",
     "Verbose logs visible in stdout"),
    ("AC-OBS-002", "US-OBS-002", "JobRunr dashboard",
     "App is running",
     "Operator opens dashboard port",
     "Dashboard UI is reachable"),
    # CROSS
    ("AC-CROSS-001", "US-CROSS-001", "CORS preflight",
     "Browser issues OPTIONS",
     "Frontend at localhost:5173 calls API",
     "Response includes Access-Control-Allow-Origin"),
    ("AC-CROSS-002", "US-CROSS-002", "API key auth",
     "Request has valid X-API-Key",
     "Service-to-service call",
     "Request is authenticated as ApiKey user"),
    ("AC-CROSS-003", "US-CROSS-003", "Read from slave",
     "ReadOnly service method invoked",
     "GET /workspace",
     "SQL runs against the slave datasource"),
    ("AC-CROSS-004", "US-CROSS-004", "Email after commit",
     "Invitation transaction commits",
     "afterCommit hook fires",
     "Email is sent only after DB commit; if commit fails no email is sent"),
]

# ===== Functional Requirements =====
functional_requirements = [
    ("FC-AUTH-001", "US-AUTH-001", "Authentication",
     "Validate credentials via Keycloak password grant and store tokens client-side",
     "username (string, 3+), password (string, 6+)",
     "POST to /realms/{realm}/protocol/openid-connect/token with grant_type=password",
     "JWT access_token, refresh_token and user profile",
     "Anonymous (unauthenticated)",
     "/realms/nckh/protocol/openid-connect/token", "POST",
     "EXPLICIT", f"{SRC_FE}/src/services/authService.ts", "authService.login"),
    ("FC-AUTH-002", "US-AUTH-002", "Authentication",
     "Register a new user in Keycloak and create the local profile",
     "firstName, lastName, dob(>=13y), username, email, password",
     "BE creates Keycloak user via Admin API with credentials",
     "ApiResponse<ProfileResponse>",
     "Anonymous",
     "/register", "POST",
     "EXPLICIT", f"{SRC_BE}/.../ProfileController.java", "register"),
    ("FC-AUTH-003", "US-AUTH-003", "Authentication",
     "On 401, refresh the access token and retry the original request",
     "Expired JWT",
     "Call /token with grant_type=refresh_token",
     "New access_token stored; original request retried",
     "End User (browser session)",
     "/realms/nckh/protocol/openid-connect/token", "POST",
     "EXPLICIT", f"{SRC_FE}/src/services/api.ts", "interceptors.response"),
    ("FC-AUTH-004", "US-AUTH-004", "Authentication",
     "Initiate OAuth2 Authorization Code with kc_idp_hint",
     "Selected IdP (google|github)",
     "Build URL with state CSRF and redirect",
     "Browser redirect to Keycloak",
     "End User",
     "/realms/nckh/protocol/openid-connect/auth", "GET",
     "EXPLICIT", f"{SRC_FE}/src/services/authService.ts", "loginWithGoogle/Github"),
    ("FC-AUTH-005", "US-AUTH-005", "Authentication",
     "Validate Bearer JWT on every backend request",
     "Authorization header",
     "Spring Security OAuth2 Resource Server with JwtAuthenticationConverter",
     "SecurityContext populated; downstream code uses subject",
     "End User / API client",
     "/**", "ANY",
     "EXPLICIT", f"{SRC_BE}/.../SecurityConfig.java", "filterChain"),
    ("FC-AUTH-006", "US-AUTH-006", "Authentication",
     "Convert any exception into ApiResponse JSON",
     "Any thrown exception",
     "GlobalExceptionHandler maps to ErrorCode + HttpStatus",
     "{code, message} JSON",
     "All roles",
     "/**", "ANY",
     "EXPLICIT", f"{SRC_BE}/.../GlobalExceptionHandler.java", "GlobalExceptionHandler"),
    ("FC-PROFILE-001", "US-PROFILE-001", "Profile",
     "Render the profile page",
     "Authenticated session",
     "Static UI with mocked data",
     "Profile view + tabs",
     "End User",
     "/profile", "GET (FE)",
     "INFERRED", f"{SRC_FE}/src/pages/Profile.tsx", "Profile component"),
    ("FC-PROFILE-002", "US-PROFILE-002", "Profile",
     "List all profiles",
     "JWT",
     "ProfileAppService.getAllProfiles",
     "ApiResponse<List<ProfileResponse>>",
     "Any authenticated user",
     "/profiles", "GET",
     "EXPLICIT", f"{SRC_BE}/.../ProfileController.java", "getAllProfiles"),
    ("FC-PROFILE-003", "US-PROFILE-002", "Profile",
     "Get current user profile",
     "JWT",
     "ProfileAppService.getMyProfile",
     "ApiResponse<ProfileResponse>",
     "End User",
     "/my-profile", "GET",
     "EXPLICIT", f"{SRC_BE}/.../ProfileController.java", "getMyProfiles"),
    ("FC-WORKSPACE-001", "US-WORKSPACE-001", "Workspace",
     "Create workspace with default roles and backlog",
     "WorkspaceCreateRequest(name, type, access)",
     "Save workspace; seed 3 roles; create default backlog; add creator as ADMIN",
     "WorkspaceResponse",
     "End User",
     "/workspace", "POST",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "createWorkspace"),
    ("FC-WORKSPACE-002", "US-WORKSPACE-002", "Workspace",
     "List workspaces of current user",
     "JWT",
     "workspaceMemberRepository.findAllByProfile_UserId",
     "ApiResponse<List<WorkspaceResponse>>",
     "End User",
     "/workspace", "GET",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "getAllWorkspaces"),
    ("FC-WORKSPACE-003", "US-WORKSPACE-003", "Workspace",
     "Update workspace metadata",
     "workspaceId, WorkspaceUpdateRequest",
     "Verify WORKSPACE_ADMINISTER then update",
     "WorkspaceResponse",
     "Workspace Admin",
     "/workspace/{workspaceId}", "PUT",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceController.java", "updateWorkspace"),
    ("FC-WORKSPACE-004", "US-WORKSPACE-004", "Workspace",
     "Delete workspace",
     "workspaceId",
     "Verify WORKSPACE_DELETE then delete",
     "ApiResponse OK",
     "Workspace Admin",
     "/workspace/{workspaceId}", "DELETE",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceController.java", "deleteWorkspace"),
    ("FC-WORKSPACE-005", "US-WORKSPACE-005", "Workspace",
     "Trigger graph rebuild",
     "workspaceId",
     "graphEventPort.sendRebuildEvent(workspaceId)",
     "200 OK 'Rebuild triggered'",
     "Workspace Admin",
     "/workspace/{workspaceId}/rebuild-graph", "POST",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceController.java", "rebuildGraph"),
    ("FC-MEMBER-001", "US-MEMBER-001", "Workspace Member",
     "List workspace members",
     "workspaceId",
     "workspaceMemberRepository.findAllByWorkspace_Id",
     "List<WorkspaceMemberResponse>",
     "Workspace Member+",
     "/workspace/{workspaceId}/members", "GET",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "getMembers"),
    ("FC-INVITE-001", "US-INVITE-001", "Invitation",
     "Create invitation and notify",
     "email + role (MEMBER|VIEWER)",
     "Validate email exists; not self; not already member; no pending; role != ADMIN",
     "ApiResponse OK + notification + afterCommit email",
     "Workspace Admin",
     "/workspace/{workspaceId}/invitations", "POST",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "inviteMemberToWorkspace"),
    ("FC-INVITE-002", "US-INVITE-002", "Invitation",
     "Accept invitation",
     "invitationId (from JWT subject)",
     "Validate status/expiry/owner; create WorkspaceMember; notify inviter",
     "Workspace id",
     "Invitee",
     "/invitations/{invitationId}/accept", "POST",
     "EXPLICIT", f"{SRC_BE}/.../InvitationAppServiceImpl.java", "accept"),
    ("FC-INVITE-003", "US-INVITE-002", "Invitation",
     "Deny invitation",
     "invitationId",
     "Validate owner; set status REJECTED; notify inviter",
     "204 No Content",
     "Invitee",
     "/invitations/{invitationId}/deny", "POST",
     "EXPLICIT", f"{SRC_BE}/.../InvitationAppServiceImpl.java", "deny"),
    ("FC-INVITE-004", "US-INVITE-003", "Invitation",
     "List my pending invitations",
     "JWT",
     "findByInviteeUserIdAndStatus",
     "List<InvitationResponse>",
     "End User",
     "/invitations/pending", "GET",
     "EXPLICIT", f"{SRC_BE}/.../InvitationController.java", "myPendingInvitations"),
    ("FC-RBAC-001", "US-RBAC-001", "RBAC",
     "Get permission matrix",
     "workspaceId",
     "Seed missing roles; map each role to permissions set",
     "List<RolePermissionMatrixResponse>",
     "Workspace Member+",
     "/workspace/{workspaceId}/permission-matrix", "GET",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleAppServiceImpl.java", "getPermissionMatrix"),
    ("FC-RBAC-002", "US-RBAC-002", "RBAC",
     "Update role permissions",
     "workspaceId, roleName, permissions",
     "Set new permissions; preserve WORKSPACE_ADMINISTER for ADMIN role",
     "RolePermissionMatrixResponse",
     "Workspace Admin",
     "/workspace/{workspaceId}/roles/{roleName}/permissions", "PUT",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleAppServiceImpl.java", "updateRolePermissions"),
    ("FC-RBAC-003", "US-RBAC-003", "RBAC",
     "Change a member's role",
     "workspaceId, userId, new role",
     "Reject if it would demote the last admin",
     "ApiResponse OK",
     "Workspace Admin",
     "/workspace/{workspaceId}/members/{userId}/role", "PUT",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleAppServiceImpl.java", "changeMemberRole"),
    ("FC-RBAC-004", "US-RBAC-004", "RBAC",
     "Manage resource grants",
     "ResourceGrantRequest",
     "Create/list/delete with optional resourceType/resourceId filters",
     "ResourceGrantResponse[]",
     "Workspace Admin",
     "/workspace/{workspaceId}/grants", "POST/GET/DELETE",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleController.java", "grants"),
    ("FC-RBAC-005", "US-RBAC-004", "RBAC",
     "Show current access for caller",
     "workspaceId",
     "Resolve roles + grants -> MyWorkspaceAccessResponse",
     "MyWorkspaceAccessResponse",
     "End User",
     "/workspace/{workspaceId}/my-access", "GET",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleController.java", "myAccess"),
    ("FC-SPRINT-001", "US-SPRINT-001", "Sprint",
     "Create sprint",
     "SprintCreateRequest",
     "Verify SPRINT_CREATE; map entity; status=ToDo",
     "SprintResponse",
     "Workspace Member+",
     "/sprints/workspace/{workspaceId}", "POST",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "createSprint"),
    ("FC-SPRINT-002", "US-SPRINT-002", "Sprint",
     "Add one or many stories to sprint",
     "List<String> userStoryIds",
     "Verify ToDo state and workspace match; assign sprint; clear backlog",
     "ApiResponse OK",
     "Workspace Member+",
     "/sprints/{sprintId}/user-stories[/{userStoryId}]", "POST",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "addUserStoriesToSprint"),
    ("FC-SPRINT-003", "US-SPRINT-003", "Sprint",
     "Start sprint",
     "sprintId",
     "Verify SPRINT_MANAGE; ensure no other active sprint; move to InProgress; publish events",
     "ApiResponse OK",
     "Workspace Member+",
     "/sprints/{sprintId}/start", "POST",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "startSprint"),
    ("FC-SPRINT-004", "US-SPRINT-004", "Sprint",
     "Complete sprint",
     "sprintId",
     "Move unfinished stories back to backlog with status=ToDo; set Done",
     "ApiResponse OK",
     "Workspace Member+",
     "/sprints/{sprintId}/complete", "POST",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "completeSprint"),
    ("FC-SPRINT-005", "US-SPRINT-005", "Sprint",
     "Remove a story from sprint",
     "userStoryId",
     "Verify SPRINT_EDIT; clear story.sprint",
     "ApiResponse OK",
     "Workspace Member+",
     "/sprints/user-stories/{userStoryId}", "DELETE",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "removeUserStoryFromSprint"),
    ("FC-SPRINT-006", "US-SPRINT-002", "Sprint",
     "Get all sprints in workspace",
     "workspaceId",
     "Find by workspace ordered by createdAt desc",
     "List<SprintResponse>",
     "Workspace Member+",
     "/sprints/workspace/{workspaceId}", "GET",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "getSprints"),
    ("FC-SPRINT-007", "US-SPRINT-002", "Sprint",
     "Get user stories of a sprint",
     "sprintId",
     "Find by sprint_id",
     "List<UserStoryResponse>",
     "Workspace Member+",
     "/sprints/{sprintId}/user-stories", "GET",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "getUserStoriesOfSprint"),
    ("FC-US-001", "US-US-001", "User Story",
     "Create stories in workspace backlog",
     "List<UserStoryCreateRequest>",
     "Map + persist; default status=ToDo; publish USER_STORY_CREATED events",
     "List<UserStoryResponse>",
     "Workspace Member+",
     "/user-stories/workspace/{workspaceId}", "POST",
     "EXPLICIT", f"{SRC_BE}/.../UserStoryAppServiceImpl.java", "create"),
    ("FC-US-002", "US-US-002", "User Story",
     "List backlog stories",
     "workspaceId",
     "Find by workspace with sprint is null",
     "List<UserStoryResponse>",
     "Workspace Member+",
     "/user-stories/workspace/{workspaceId}/backlog", "GET",
     "EXPLICIT", f"{SRC_BE}/.../UserStoryAppServiceImpl.java", "getBacklog"),
    ("FC-US-003", "US-US-003", "User Story",
     "Update story status",
     "userStoryId + new status",
     "Verify ISSUE_TRANSITION; story in active sprint; valid status enum",
     "UserStoryResponse",
     "Workspace Member+",
     "/user-stories/{userStoryId}/status", "PUT",
     "EXPLICIT", f"{SRC_BE}/.../UserStoryAppServiceImpl.java", "updateStatus"),
    ("FC-US-004", "US-US-004", "User Story",
     "Delete story",
     "userStoryId",
     "Verify ISSUE_DELETE; delete",
     "ApiResponse OK",
     "Workspace Member+",
     "/user-stories/{userStoryId}", "DELETE",
     "EXPLICIT", f"{SRC_BE}/.../UserStoryAppServiceImpl.java", "delete"),
    ("FC-US-005", "US-US-002", "User Story",
     "Get single story",
     "userStoryId",
     "Find by id; verify ISSUE_VIEW",
     "UserStoryResponse",
     "Workspace Member+",
     "/user-stories/{id}", "GET",
     "EXPLICIT", f"{SRC_BE}/.../UserStoryController.java", "getById"),
    ("FC-NOTIF-001", "US-NOTIF-001", "Notification",
     "List unread notifications",
     "JWT subject",
     "findByUserIdAndReadFalseOrderByCreatedAtDesc",
     "List<NotificationResponse>",
     "End User",
     "/notifications/unread", "GET",
     "EXPLICIT", f"{SRC_BE}/.../NotificationAppServiceImpl.java", "getUnread"),
    ("FC-NOTIF-002", "US-NOTIF-002", "Notification",
     "Mark one notification as read",
     "notificationId + JWT subject",
     "Validate ownership; set read=true",
     "ApiResponse OK",
     "Owner only",
     "/notifications/{id}/read", "PATCH",
     "EXPLICIT", f"{SRC_BE}/.../NotificationController.java", "markAsRead"),
    ("FC-NOTIF-003", "US-NOTIF-002", "Notification",
     "Mark all as read",
     "JWT subject",
     "markAllAsReadByUserId",
     "ApiResponse OK",
     "End User",
     "/notifications/read-all", "PATCH",
     "EXPLICIT", f"{SRC_BE}/.../NotificationController.java", "markAllAsRead"),
    ("FC-NOTIF-004", "US-NOTIF-003", "Notification",
     "Send realtime notification if online",
     "userId + payload",
     "Persist + push via RealtimeNotificationPort if online",
     "Notification saved; optional WS push",
     "End User",
     "(internal)", "INTERNAL",
     "EXPLICIT", f"{SRC_BE}/.../NotificationAppServiceImpl.java", "notifyUser"),
    ("FC-GRAPH-001", "US-GRAPH-001", "Graph",
     "Query workspace similarity/association graph",
     "workspaceId, sprintId?, backlogId?, source, includeSimilarity, includeAssociation, minScore, minConfidence",
     "Validate source; run Cypher on Neo4j; build nodes + edges",
     "GraphResponse{nodes,edges}",
     "Workspace Member+",
     "/graphql", "POST",
     "EXPLICIT", f"{SRC_BE}/.../GraphQueryResolver.java", "workspaceGraph"),
    ("FC-GRAPH-002", "US-GRAPH-002", "Graph",
     "Filter graph by sprint/backlog",
     "sprintId or backlogId",
     "Apply additional WHERE clauses in Cypher",
     "Filtered GraphResponse",
     "Workspace Member+",
     "/graphql", "POST",
     "EXPLICIT", f"{SRC_BE}/.../GraphServiceImpl.java", "getWorkspaceGraph"),
    ("FC-OBS-001", "US-OBS-001", "Observability",
     "Enable DEBUG logging",
     "Environment",
     "Set logging.level.*=DEBUG",
     "Detailed logs visible",
     "Operator",
     "(config)", "N/A",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "logging.level"),
    ("FC-OBS-002", "US-OBS-002", "Observability",
     "Enable JobRunr background job server + dashboard",
     "Environment",
     "jobrunr.background-job-server.enabled=true",
     "Background jobs run; dashboard reachable",
     "Operator",
     "(config)", "N/A",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "jobrunr.*"),
    ("FC-CROSS-001", "US-CROSS-001", "Cross-cutting",
     "Enable CORS for SPA",
     "Browser preflight",
     "CorsConfigurationSource with allowedOriginPatterns='*'",
     "Access-Control-Allow-Origin present",
     "All callers",
     "/**", "OPTIONS",
     "EXPLICIT", f"{SRC_BE}/.../SecurityConfig.java", "corsConfigurationSource"),
    ("FC-CROSS-002", "US-CROSS-002", "Cross-cutting",
     "Authenticate via X-API-Key",
     "X-API-Key header",
     "ApiKeyFilter validates the key",
     "SecurityContext populated with ApiKey principal",
     "Service clients",
     "/**", "ANY",
     "EXPLICIT", f"{SRC_BE}/.../ApiKeyFilter.java", "ApiKeyFilter"),
    ("FC-CROSS-003", "US-CROSS-003", "Cross-cutting",
     "Route reads to slave, writes to master",
     "@ReadOnly methods",
     "RoutingDataSource + DataSourceContextHolder",
     "Reads executed on slave datasource",
     "Internal",
     "(internal)", "INTERNAL",
     "EXPLICIT", f"{SRC_BE}/.../DataSourceConfig.java", "DataSourceConfig"),
    ("FC-CROSS-004", "US-CROSS-004", "Cross-cutting",
     "Send email only after commit",
     "Invitation service",
     "TransactionSynchronization.afterCommit",
     "Email dispatched only on commit success",
     "Internal",
     "(internal)", "INTERNAL",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "registerSynchronization"),
]

# ===== Non-Functional Requirements =====
non_functional = [
    ("NFC-SECURITY-001", "Security", "JWT authentication on every protected endpoint",
     "All endpoints except /register and /error require a valid Bearer JWT",
     "OAuth2 Resource Server JWT; PUBLIC_ENDPOINTS only '/register','/error'",
     "E2E: auth.spec verifies anonymous /workspace redirects to /login",
     "EXPLICIT", f"{SRC_BE}/.../SecurityConfig.java", "SecurityConfig.filterChain",
     "JWT signature and exp are validated by Keycloak issuer"),
    ("NFC-SECURITY-002", "Security", "Role-based access control (Jira-style)",
     "33 distinct Permissions checked at service boundary",
     "WorkspaceAccessService.require / requireSprint / requireUserStory",
     "Domain unit tests on DefaultPermissionMatrix and AccessEvaluator",
     "EXPLICIT", "be/nckh/nckh-domain/src/main/java/com/xxxx/dddd/domain/model/enums/Permission.java", "Permission enum",
     "Each permission name maps to a resource:Action pair (e.g. issue:Edit)"),
    ("NFC-SECURITY-003", "Security", "Resource-level ACL overrides",
     "Per-resource grants for fine-grained control",
     "ResourceGrant entity + ResourceGrantRepository",
     "Granted via /workspace/{id}/grants; covered by FE/WorkspaceRoleController",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceRoleController.java", "createGrant/listGrants/deleteGrant",
     "ACL overrides the default role-based permission"),
    ("NFC-SECURITY-004", "Security", "OAuth2/OIDC login delegated to Keycloak",
     "No passwords stored in this service",
     "Keycloak issues access_token + refresh_token",
     "Tokens are JWTs signed by Keycloak",
     "EXPLICIT", f"{SRC_BE}/.../IdentityServiceImpl.java", "IdentityServiceImpl",
     "Keycloak as IdP; supports Google/GitHub social login"),
    ("NFC-SECURITY-005", "Security", "API key authentication",
     "Service-to-service calls authenticate via X-API-Key",
     "ApiKeyFilter intercepts and validates",
     "API key in env (X-API-Key)",
     "EXPLICIT", f"{SRC_BE}/.../ApiKeyFilter.java", "ApiKeyFilter",
     "Configurable in env; rotate via secret manager"),
    ("NFC-SECURITY-006", "Security", "Self-invite / cross-workspace rejected",
     "User cannot invite themselves or operate outside their workspace",
     "Validation in WorkspaceAppServiceImpl / SprintAppServiceImpl",
     "Integration tests should cover, currently no automated test",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "inviteMemberToWorkspace",
     "Exhaustively tested via API contract; no test class"),
    ("NFC-PERFORMANCE-001", "Performance", "Read/write DB routing",
     "Reads served from slave, writes from master",
     "RoutingDataSource + @ReadOnly annotation",
     "Configured via HikariCP pool; observe in metrics",
     "EXPLICIT", f"{SRC_BE}/.../DataSourceConfig.java", "DataSourceConfig",
     "Specific throughput SLA is NOT defined in code"),
    ("NFC-PERFORMANCE-002", "Performance", "Redis caching",
     "Redis configured as caching layer",
     "spring.data.redis.* properties",
     "No explicit test for cache hit rate",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "spring.data.redis",
     "Cache hit-rate, latency SLA not defined"),
    ("NFC-RELIABILITY-001", "Reliability", "Event publishing after transaction commit",
     "Sprint start/complete and story creation publish events only after commit",
     "TransactionalEvents.afterCommit / TransactionSynchronizationManager",
     "Unit/integration tests not present",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "afterCommit hooks",
     "Avoids publishing events for transactions that get rolled back"),
    ("NFC-RELIABILITY-002", "Reliability", "Email send only after DB commit",
     "Invitation email is queued via afterCommit",
     "TransactionSynchronizationManager.registerSynchronization",
     "No regression test present",
     "EXPLICIT", f"{SRC_BE}/.../WorkspaceAppServiceImpl.java", "afterCommit",
     "Prevents emailing about un-committed invitations"),
    ("NFC-RELIABILITY-003", "Reliability", "Consistent error JSON contract",
     "All errors map to ApiResponse{code,message}",
     "GlobalExceptionHandler + ErrorCode enum",
     "Manual contract test (Playwright UI smoke)",
     "EXPLICIT", f"{SRC_BE}/.../GlobalExceptionHandler.java", "GlobalExceptionHandler",
     "30+ ErrorCodes with stable numeric codes"),
    ("NFC-AVAILABILITY-001", "Availability", "Background jobs processed via JobRunr",
     "JobRunr server enabled",
     "jobrunr.background-job-server.enabled=true",
     "Dashboard available on configured port",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "jobrunr.background-job-server",
     "Specific uptime SLA not defined"),
    ("NFC-AVAILABILITY-002", "Availability", "MySQL Master/Slave replication",
     "Replication configured via docker-compose",
     "mysql-replication/docker-compose.yml",
     "Manual verification per README",
     "EXPLICIT", f"{SRC_BE}/mysql-replication/docker-compose.yml", "docker-compose",
     "Automatic failover not implemented in code"),
    ("NFC-SCALABILITY-001", "Scalability", "Master/slave DB separation",
     "Reads scale horizontally via slave nodes",
     "RoutingDataSource abstracts slave selection",
     "Manual; no automated load test",
     "EXPLICIT", f"{SRC_BE}/.../DataSourceConfig.java", "DataSourceConfig",
     "Add more slave replicas by adding HikariCP pools"),
    ("NFC-SCALABILITY-002", "Scalability", "Async event messaging",
     "RabbitMQ used for messaging",
     "RabbitConfig + RabbitMQMessageConfig",
     "No throughput SLA defined",
     "EXPLICIT", f"{SRC_BE}/.../rmq/RabbitConfig.java", "RabbitConfig",
     "Add more consumers to scale processing"),
    ("NFC-MAINTAINABILITY-001", "Maintainability", "Layered DDD architecture",
     "Clear separation controller -> application -> domain -> infrastructure",
     "Maven modules nckh-controller/application/domain/infrastructure",
     "Build + unit tests run via Maven",
     "EXPLICIT", f"{SRC_BE}/nckh/pom.xml", "Maven module structure",
     "Java 21 + Spring Boot 3 stack"),
    ("NFC-MAINTAINABILITY-002", "Maintainability", "Stable ErrorCode enum",
     "Numeric codes + HTTP status for every error",
     "ErrorCode enum (30+ codes)",
     "Manual code review",
     "EXPLICIT", f"{SRC_BE}/.../common/exception/ErrorCode.java", "ErrorCode",
     "Codes stable across releases"),
    ("NFC-MAINTAINABILITY-003", "Maintainability", "Playwright E2E coverage",
     "6 spec files for FE flows",
     "npm run test:e2e",
     "Run via Playwright",
     "EXPLICIT", f"{SRC_FE}/tests/e2e/*.spec.ts", "Playwright specs",
     "Members of frontend flows covered: auth/nav/workspace/sprint/backlog/ui"),
    ("NFC-OBSERVABILITY-001", "Observability", "Spring Security DEBUG logs",
     "DEBUG for org.springframework.security, spring-web, com.xxxx.backend_mvc",
     "logging.level config",
     "Manual inspection",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "logging.level",
     "Could be tightened in production via env"),
    ("NFC-OBSERVABILITY-002", "Observability", "JobRunr dashboard",
     "Dashboard enabled on configurable port",
     "jobrunr.dashboard",
     "Operator opens browser",
     "EXPLICIT", f"{SRC_BE}/nckh-start/src/main/resources/application.yml", "jobrunr.dashboard",
     "Should be protected in production"),
    ("NFC-OBSERVABILITY-003", "Observability", "WebSocket realtime notifications",
     "Online users receive push notifications",
     "RealtimeNotificationPort + SocketService",
     "No automated test for WS push",
     "EXPLICIT", f"{SRC_BE}/.../NotificationAppServiceImpl.java", "notifyUser",
     "Heartbeat/presence mechanism not visible in code"),
    ("NFC-DATA-INTEGRITY-001", "Data integrity", "Transactional service methods",
     "@Transactional ensures atomicity",
     "@Transactional on SprintAppServiceImpl, UserStoryAppServiceImpl, etc.",
     "No explicit integration test for rollback",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "@Transactional",
     "Inside method invocation by self-bypass proxy is not an issue here (cross-bean call)"),
    ("NFC-DATA-INTEGRITY-002", "Data integrity", "ReadOnly transactions for queries",
     "@ReadOnly routes to slave and uses readOnly tx",
     "ReadOnly annotation + JpaTransactionConfig",
     "No automated test",
     "EXPLICIT", f"{SRC_BE}/.../SprintAppServiceImpl.java", "@ReadOnly on getSprints",
     "Slave lag may cause stale reads"),
    ("NFC-COMPATIBILITY-001", "Compatibility", "Java 21 + Spring Boot 3",
     "Spring Boot 3.x",
     "pom.xml",
     "Build with mvn package",
     "EXPLICIT", f"{SRC_BE}/nckh/pom.xml", "pom.xml",
     "Need JDK 21+ to build"),
    ("NFC-COMPATIBILITY-002", "Compatibility", "React 18 SPA",
     "Vite + React 18 + Redux Toolkit + TanStack Query + dnd-kit",
     "package.json",
     "npm run build",
     "EXPLICIT", f"{SRC_FE}/package.json", "package.json",
     "Browsers targets set by Vite defaults"),
    ("NFC-USABILITY-001", "Usability", "Login supports Google/GitHub",
     "Social login buttons on LoginPage",
     "LoginPage.tsx with loginWithGoogle/loginWithGithub",
     "Manual; no automated test",
     "EXPLICIT", f"{SRC_FE}/src/pages/auth/LoginPage.tsx", "LoginPage buttons",
     "Visual: LoginPage renders buttons, redirects to Keycloak"),
    ("NFC-USABILITY-002", "Usability", "Multi-step registration wizard",
     "4-step wizard with progress indicator and password strength meter",
     "RegisterPage.tsx validateStep",
     "Manual; no automated test",
     "EXPLICIT", f"{SRC_FE}/src/pages/auth/RegisterPage.tsx", "RegisterPage.validateStep",
     "Strong UX: dots indicator, eye toggle for password"),
]

# ===== Test Cases =====
test_cases = [
    # ---- AUTH ----
    ("TC-AUTH-001", "US-AUTH-001", "AC-AUTH-001", "FC-AUTH-001", "Authentication",
     "Login with valid credentials", "E2E (Playwright)", "High",
     "User 'duchuy1' exists in Keycloak",
     "1. Goto /login 2. Fill username 'duchuy1' 3. Fill password 'duchuy123' 4. Click submit",
     "username=duchuy1, password=duchuy123",
     "Redirect to '/' within 10s", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/auth.spec.ts", "/realms/nckh/token",
     "Happy path - covers US-AUTH-001 + Keycloak integration"),
    ("TC-AUTH-002", "US-AUTH-001", "AC-AUTH-002", "FC-AUTH-001", "Authentication",
     "Login with invalid credentials", "E2E (Playwright)", "High",
     "Logged out",
     "1. Goto /login 2. Submit empty form",
     "empty fields",
     "Form is not submitted; stays on /login", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/auth.spec.ts", "/login",
     "Validates required fields client-side"),
    ("TC-AUTH-003", "US-AUTH-002", "AC-AUTH-003", "FC-AUTH-002", "Authentication",
     "Registration wizard step validation", "E2E (Playwright)", "High",
     "User is on /register step 1",
     "1. Click Next without filling name fields",
     "empty fields",
     "Inline error appears; user stays on step 1", "PROPOSED",
     "PROPOSED", "n/a (frontend/src/pages/auth/RegisterPage.tsx)", "/register",
     "Covered by client validation logic; no E2E spec yet"),
    ("TC-AUTH-004", "US-AUTH-002", "AC-AUTH-004", "FC-AUTH-002", "Authentication",
     "Reject under-13 DOB", "E2E (Playwright)", "Medium",
     "User is on step 2 (DOB)",
     "1. Enter today's date as DOB",
     "dob=today",
     "Error: 'You must be at least 13 years old'", "PROPOSED",
     "PROPOSED", "n/a", "/register",
     "Implementation present; no E2E"),
    ("TC-AUTH-005", "US-AUTH-003", "AC-AUTH-005", "FC-AUTH-003", "Authentication",
     "Auto refresh on 401", "E2E (Playwright)", "High",
     "Access token has expired but refresh token is valid",
     "1. Trigger an authenticated request after expiry",
     "expired access token",
     "Refresh succeeds; original request retries", "PROPOSED",
     "PROPOSED", "n/a", "/api/refresh",
     "Logic implemented in api.ts; no E2E"),
    ("TC-AUTH-006", "US-AUTH-003", "AC-AUTH-006", "FC-AUTH-003", "Authentication",
     "Redirect to login when refresh fails", "E2E (Playwright)", "High",
     "Refresh token missing or invalid",
     "1. Remove refresh token from localStorage 2. Trigger request after expiry",
     "no refresh token",
     "Redirect to /login", "PROPOSED",
     "PROPOSED", "n/a", "/login",
     "Implemented; needs E2E"),
    ("TC-AUTH-007", "US-AUTH-005", "AC-AUTH-008", "FC-AUTH-005", "Authentication",
     "Unauthenticated request rejected", "E2E (Playwright)", "High",
     "No token in localStorage",
     "1. Navigate to /workspace/test-id",
     "no token",
     "Redirect to /login", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/navigation.spec.ts", "/login",
     "navigation.spec 'Route Protection'"),
    ("TC-AUTH-008", "US-AUTH-005", "AC-AUTH-009", "FC-AUTH-005", "Authentication",
     "Authenticated request accepted", "Integration", "High",
     "Valid JWT",
     "1. GET /my-profile with Bearer token",
     "JWT",
     "200 with ApiResponse code=1000", "PROPOSED",
     "PROPOSED", "n/a", "/my-profile",
     "Manual smoke only"),
    ("TC-AUTH-009", "US-OBS-001", "AC-OBS-001", "FC-OBS-001", "Authentication",
     "Security DEBUG logging enabled", "Configuration", "Low",
     "App started with default env",
     "1. Inspect log output for 'DEBUG org.springframework.security'",
     "n/a",
     "Logs present", "PROPOSED",
     "PROPOSED", "n/a", "/log",
     "Set in application.yml"),
    # ---- WORKSPACE ----
    ("TC-WORKSPACE-001", "US-WORKSPACE-001", "AC-WORKSPACE-001", "FC-WORKSPACE-001", "Workspace",
     "Create workspace via UI", "E2E (Playwright)", "High",
     "Logged in user",
     "1. Goto /workspace/create 2. Fill name 3. Submit",
     "name='E2E Workspace'",
     "Redirect to /workspace/{id}/invite", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/workspace.spec.ts", "/workspace",
     "workspace.spec navigates to /workspace/create"),
    ("TC-WORKSPACE-002", "US-WORKSPACE-002", "AC-WORKSPACE-002", "FC-WORKSPACE-002", "Workspace",
     "List my workspaces", "E2E (Playwright)", "High",
     "User has at least one workspace",
     "1. Goto / 2. Inspect workspace cards",
     "n/a",
     "Cards visible", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/workspace.spec.ts", "/workspace",
     "workspace.spec verifies list display"),
    ("TC-WORKSPACE-003", "US-WORKSPACE-003", "AC-WORKSPACE-003", "FC-WORKSPACE-003", "Workspace",
     "Non-admin cannot update workspace", "Integration", "High",
     "Caller is VIEWER",
     "1. PUT /workspace/{id}",
     "role=VIEWER",
     "403 with code 1007", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}",
     "Behaviour confirmed in code"),
    ("TC-WORKSPACE-004", "US-WORKSPACE-004", "AC-WORKSPACE-004", "FC-WORKSPACE-004", "Workspace",
     "Admin can delete workspace", "Integration", "High",
     "Caller is ADMIN",
     "1. DELETE /workspace/{id}",
     "role=ADMIN",
     "200 OK", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}",
     "No test present"),
    ("TC-WORKSPACE-005", "US-WORKSPACE-005", "AC-WORKSPACE-005", "FC-WORKSPACE-005", "Workspace",
     "Trigger rebuild graph", "Integration", "Low",
     "Caller is ADMIN",
     "1. POST /workspace/{id}/rebuild-graph",
     "role=ADMIN",
     "200 'Rebuild triggered'", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/rebuild-graph",
     "Code-only behaviour"),
    # ---- MEMBER ----
    ("TC-MEMBER-001", "US-MEMBER-001", "AC-MEMBER-001", "FC-MEMBER-001", "Workspace Member",
     "List members", "Integration", "Medium",
     "Caller is MEMBER",
     "1. GET /workspace/{id}/members",
     "n/a",
     "200 List<WorkspaceMemberResponse>", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/members",
     "No test present"),
    # ---- INVITE ----
    ("TC-INVITE-001", "US-INVITE-001", "AC-INVITE-001", "FC-INVITE-001", "Invitation",
     "Send invitation happy path", "Unit + Integration", "High",
     "Inviter is ADMIN; invitee exists; no existing member/pending",
     "1. POST /workspace/{id}/invitations {email,role}",
     "email=existing@x.com, role=MEMBER",
     "200 OK; notification created; email queued afterCommit", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/invitations",
     "Behaviour present in code"),
    ("TC-INVITE-002", "US-INVITE-001", "AC-INVITE-002", "FC-INVITE-001", "Invitation",
     "Reject self-invite", "Unit", "High",
     "Inviter email == invitee email",
     "1. POST /workspace/{id}/invitations with own email",
     "self email",
     "Error 1016 INVALID_INVITE", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/invitations",
     "Logic present"),
    ("TC-INVITE-003", "US-INVITE-001", "AC-INVITE-003", "FC-INVITE-001", "Invitation",
     "Reject ADMIN invite", "Unit", "High",
     "Inviter tries role=ADMIN",
     "1. POST invitation with role=ADMIN",
     "role=ADMIN",
     "Error 1032 INVALID_ROLE", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/invitations",
     "Logic present"),
    ("TC-INVITE-004", "US-INVITE-001", "AC-INVITE-004", "FC-INVITE-001", "Invitation",
     "Reject duplicate pending", "Unit", "Medium",
     "Pending invitation already exists",
     "1. POST same invitation twice",
     "duplicate",
     "Error 1019 INVITATION_ALREADY_SENT", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/invitations",
     "Logic present"),
    ("TC-INVITE-005", "US-INVITE-002", "AC-INVITE-005", "FC-INVITE-002", "Invitation",
     "Accept invitation happy path", "Unit + Integration", "High",
     "Invitee logged in; status=PENDING; not expired; not a member yet",
     "1. POST /invitations/{id}/accept",
     "valid invitation",
     "WorkspaceMember created; inviter notified", "PROPOSED",
     "PROPOSED", "n/a", "/invitations/{id}/accept",
     "Logic present"),
    ("TC-INVITE-006", "US-INVITE-002", "AC-INVITE-006", "FC-INVITE-002", "Invitation",
     "Accept wrong user", "Unit", "High",
     "Caller is not the invitee",
     "1. POST accept from another account",
     "other user JWT",
     "Error 1014 NO_PERMISSION", "PROPOSED",
     "PROPOSED", "n/a", "/invitations/{id}/accept",
     "Logic present"),
    ("TC-INVITE-007", "US-INVITE-002", "AC-INVITE-007", "FC-INVITE-002", "Invitation",
     "Accept expired", "Unit", "High",
     "expiredAt < now",
     "1. POST accept after expiry",
     "expired",
     "Error 1018 INVITE_EXPIRED", "PROPOSED",
     "PROPOSED", "n/a", "/invitations/{id}/accept",
     "Logic present"),
    ("TC-INVITE-008", "US-INVITE-002", "AC-INVITE-008", "FC-INVITE-003", "Invitation",
     "Deny invitation", "Unit", "High",
     "Valid pending invitation",
     "1. POST /invitations/{id}/deny",
     "valid",
     "Status -> REJECTED; inviter notified", "PROPOSED",
     "PROPOSED", "n/a", "/invitations/{id}/deny",
     "Logic present"),
    ("TC-INVITE-009", "US-INVITE-003", "AC-INVITE-009", "FC-INVITE-004", "Invitation",
     "List my pending", "Unit", "Medium",
     "Caller has pending invitations",
     "1. GET /invitations/pending",
     "n/a",
     "200 List<InvitationResponse>", "PROPOSED",
     "PROPOSED", "n/a", "/invitations/pending",
     "Logic present"),
    # ---- RBAC ----
    ("TC-RBAC-001", "US-RBAC-001", "AC-RBAC-001", "FC-RBAC-001", "RBAC",
     "Permission matrix returned", "Unit", "High",
     "Caller is MEMBER",
     "1. GET /workspace/{id}/permission-matrix",
     "n/a",
     "200 with ADMIN/MEMBER/VIEWER rows", "PASS",
     "AUTOMATED", "be/nckh/nckh-domain/src/test/java/com/xxxx/dddd/domain/model/permission/DefaultPermissionMatrixTest.java", "/workspace/{id}/permission-matrix",
     "Domain unit test verifies the matrix mapping"),
    ("TC-RBAC-002", "US-RBAC-002", "AC-RBAC-002", "FC-RBAC-002", "RBAC",
     "Cannot strip admin flag", "Unit", "High",
     "Caller is admin",
     "1. PUT /workspace/{id}/roles/ADMIN/permissions without WORKSPACE_ADMINISTER",
     "missing admin perm",
     "Service re-adds WORKSPACE_ADMINISTER", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/roles/ADMIN/permissions",
     "Logic present"),
    ("TC-RBAC-003", "US-RBAC-003", "AC-RBAC-003", "FC-RBAC-003", "RBAC",
     "Last admin cannot be demoted", "Unit", "High",
     "Workspace has 1 admin",
     "1. PUT /workspace/{id}/members/{adminId}/role MEMBER",
     "last admin",
     "Error 1031 CANNOT_DEMOTE_LAST_ADMIN", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/members/{userId}/role",
     "Logic present"),
    ("TC-RBAC-004", "US-RBAC-004", "AC-RBAC-004", "FC-RBAC-004", "RBAC",
     "Resource grant CRUD", "Unit", "High",
     "Caller is admin",
     "1. POST /workspace/{id}/grants 2. GET .../grants 3. DELETE .../grants/{id}",
     "grant",
     "Create/list/delete return expected payloads", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/grants",
     "Logic present"),
    # ---- SPRINT ----
    ("TC-SPRINT-001", "US-SPRINT-001", "AC-SPRINT-001", "FC-SPRINT-001", "Sprint",
     "Create sprint", "Unit + Integration", "High",
     "Caller has SPRINT_CREATE",
     "1. POST /sprints/workspace/{id}",
     "SprintCreateRequest",
     "200 SprintResponse with status=ToDo", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/workspace/{id}",
     "E2E: sprint.spec opens Create Sprint dialog"),
    ("TC-SPRINT-002", "US-SPRINT-001", "AC-SPRINT-001", "FC-SPRINT-001", "Sprint",
     "Sprint dialog renders fields", "E2E (Playwright)", "Medium",
     "Logged in; backlog page open",
     "1. Click 'Start Sprint' 2. Verify inputs",
     "n/a",
     "Name + date inputs visible", "PASS",
     "AUTOMATED", f"{SRC_FE}/tests/e2e/sprint.spec.ts", "/workspace/{id}/backlog",
     "sprint.spec verifies dialog"),
    ("TC-SPRINT-003", "US-SPRINT-002", "AC-SPRINT-002", "FC-SPRINT-002", "Sprint",
     "Add story to sprint OK", "Unit", "High",
     "Sprint ToDo; story same workspace",
     "1. POST /sprints/{id}/user-stories/{usId}",
     "storyId",
     "200 OK; story.sprint set; story.backlog cleared", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/user-stories/{usId}",
     "Logic present"),
    ("TC-SPRINT-004", "US-SPRINT-002", "AC-SPRINT-003", "FC-SPRINT-002", "Sprint",
     "Cross-workspace story rejected", "Unit", "High",
     "Story in different workspace",
     "1. POST add-story",
     "foreign storyId",
     "Error 1024 INVALID_WORKSPACE", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/user-stories",
     "Logic present"),
    ("TC-SPRINT-005", "US-SPRINT-002", "AC-SPRINT-004", "FC-SPRINT-002", "Sprint",
     "Missing story rejected", "Unit", "Medium",
     "Some IDs don't exist",
     "1. POST /sprints/{id}/user-stories",
     "missing ids",
     "Error 1023 USER_STORY_NOT_FOUND", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/user-stories",
     "Logic present"),
    ("TC-SPRINT-006", "US-SPRINT-003", "AC-SPRINT-005", "FC-SPRINT-003", "Sprint",
     "Start sprint OK", "Unit + Integration", "High",
     "Sprint ToDo; no active sprint",
     "1. POST /sprints/{id}/start",
     "n/a",
     "200 OK; status=InProgress; events published", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/start",
     "Logic present"),
    ("TC-SPRINT-007", "US-SPRINT-003", "AC-SPRINT-006", "FC-SPRINT-003", "Sprint",
     "Cannot start when another sprint active", "Unit", "High",
     "An InProgress sprint exists",
     "1. POST /sprints/{otherId}/start",
     "n/a",
     "Error 1022 SPRINT_ALREADY_ACTIVE", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/start",
     "Logic present"),
    ("TC-SPRINT-008", "US-SPRINT-003", "AC-SPRINT-007", "FC-SPRINT-003", "Sprint",
     "Cannot start from non-ToDo state", "Unit", "Medium",
     "Sprint already Done",
     "1. POST start",
     "n/a",
     "Error 1021 SPRINT_INVALID_STATE", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/start",
     "Logic present"),
    ("TC-SPRINT-009", "US-SPRINT-004", "AC-SPRINT-008", "FC-SPRINT-004", "Sprint",
     "Complete sprint", "Unit + Integration", "High",
     "Sprint InProgress",
     "1. POST /sprints/{id}/complete",
     "n/a",
     "Status -> Done; unfinished stories moved to backlog with ToDo", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/{id}/complete",
     "Logic present"),
    ("TC-SPRINT-010", "US-SPRINT-005", "AC-SPRINT-009", "FC-SPRINT-005", "Sprint",
     "Remove story from sprint", "Unit", "Medium",
     "Caller has SPRINT_EDIT",
     "1. DELETE /sprints/user-stories/{usId}",
     "storyId",
     "200 OK; story.sprint cleared", "PROPOSED",
     "PROPOSED", "n/a", "/sprints/user-stories/{usId}",
     "Logic present"),
    # ---- USER STORY ----
    ("TC-US-001", "US-US-001", "AC-US-001", "FC-US-001", "User Story",
     "Create stories", "Unit + Integration", "High",
     "Caller has ISSUE_CREATE",
     "1. POST /user-stories/workspace/{id} with array",
     "List<UserStoryCreateRequest>",
     "200 List<UserStoryResponse>; events published", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/workspace/{id}",
     "E2E backlog.spec verifies add-story UI"),
    ("TC-US-002", "US-US-002", "AC-US-002", "FC-US-002", "User Story",
     "Backlog list", "Unit", "High",
     "Workspace exists",
     "1. GET /user-stories/workspace/{id}/backlog",
     "n/a",
     "200 List<UserStoryResponse> (sprint is null)", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/workspace/{id}/backlog",
     "E2E backlog.spec verifies backlog page"),
    ("TC-US-003", "US-US-003", "AC-US-003", "FC-US-003", "User Story",
     "Update status OK", "Unit", "High",
     "Story in InProgress sprint",
     "1. PUT /user-stories/{id}/status",
     "new status",
     "200 UserStoryResponse", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/{id}/status",
     "Logic present"),
    ("TC-US-004", "US-US-003", "AC-US-004", "FC-US-003", "User Story",
     "Reject update when story not in sprint", "Unit", "Medium",
     "Story.sprint is null",
     "1. PUT status",
     "n/a",
     "Error 1026 USER_STORY_NOT_IN_SPRINT", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/{id}/status",
     "Logic present"),
    ("TC-US-005", "US-US-003", "AC-US-005", "FC-US-003", "User Story",
     "Reject update when sprint not active", "Unit", "Medium",
     "Sprint status != InProgress",
     "1. PUT status",
     "n/a",
     "Error 1027 SPRINT_NOT_ACTIVE", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/{id}/status",
     "Logic present"),
    ("TC-US-006", "US-US-004", "AC-US-006", "FC-US-004", "User Story",
     "Delete story", "Unit", "Medium",
     "Caller has ISSUE_DELETE",
     "1. DELETE /user-stories/{id}",
     "n/a",
     "200 OK", "PROPOSED",
     "PROPOSED", "n/a", "/user-stories/{id}",
     "Logic present"),
    # ---- NOTIFICATION ----
    ("TC-NOTIF-001", "US-NOTIF-001", "AC-NOTIF-001", "FC-NOTIF-001", "Notification",
     "Unread list", "Unit", "Medium",
     "Caller has unread notifications",
     "1. GET /notifications/unread",
     "n/a",
     "200 List<NotificationResponse>", "PROPOSED",
     "PROPOSED", "n/a", "/notifications/unread",
     "Logic present"),
    ("TC-NOTIF-002", "US-NOTIF-002", "AC-NOTIF-002", "FC-NOTIF-002", "Notification",
     "Mark single notification read", "Unit", "Medium",
     "Caller is owner",
     "1. PATCH /notifications/{id}/read",
     "n/a",
     "200 OK; read=true", "PROPOSED",
     "PROPOSED", "n/a", "/notifications/{id}/read",
     "Logic present"),
    ("TC-NOTIF-003", "US-NOTIF-002", "AC-NOTIF-003", "FC-NOTIF-003", "Notification",
     "Mark all as read", "Unit", "Medium",
     "Caller has unread",
     "1. PATCH /notifications/read-all",
     "n/a",
     "200 OK", "PROPOSED",
     "PROPOSED", "n/a", "/notifications/read-all",
     "Logic present"),
    ("TC-NOTIF-004", "US-NOTIF-003", "AC-NOTIF-004", "FC-NOTIF-004", "Notification",
     "Realtime push to online user", "Integration", "Medium",
     "Caller is online",
     "1. Server emits notification 2. Verify WS message received",
     "n/a",
     "WS frame received AND DB row persisted", "PROPOSED",
     "PROPOSED", "n/a", "/ws",
     "Logic present; needs WS integration test"),
    # ---- GRAPH ----
    ("TC-GRAPH-001", "US-GRAPH-001", "AC-GRAPH-001", "FC-GRAPH-001", "Graph",
     "Query workspace graph", "Integration", "High",
     "Caller has WORKSPACE_BROWSE",
     "1. POST /graphql workspaceGraph(workspaceId)",
     "workspaceId",
     "200 GraphResponse with nodes + edges", "PROPOSED",
     "PROPOSED", "n/a", "/graphql",
     "Logic present"),
    ("TC-GRAPH-002", "US-GRAPH-001", "AC-GRAPH-002", "FC-GRAPH-001", "Graph",
     "Reject invalid source", "Integration", "High",
     "Caller passes source=INVALID",
     "1. POST /graphql",
     "source=INVALID",
     "IllegalArgumentException", "PROPOSED",
     "PROPOSED", "n/a", "/graphql",
     "Logic present"),
    ("TC-GRAPH-003", "US-GRAPH-002", "AC-GRAPH-003", "FC-GRAPH-002", "Graph",
     "Filter by sprintId", "Integration", "Medium",
     "Caller provides sprintId",
     "1. POST /graphql workspaceGraph(workspaceId, sprintId)",
     "sprintId",
     "Edges only scoped to that sprint", "PROPOSED",
     "PROPOSED", "n/a", "/graphql",
     "Logic present"),
    # ---- CROSS-CUTTING ----
    ("TC-CROSS-001", "US-CROSS-001", "AC-CROSS-001", "FC-CROSS-001", "Cross-cutting",
     "CORS preflight OK", "Integration", "Medium",
     "Browser at http://localhost:5173",
     "1. OPTIONS /workspace",
     "Origin=http://localhost:5173",
     "Access-Control-Allow-Origin present", "PROPOSED",
     "PROPOSED", "n/a", "/**",
     "Logic present in SecurityConfig"),
    ("TC-CROSS-002", "US-CROSS-002", "AC-CROSS-002", "FC-CROSS-002", "Cross-cutting",
     "API key auth", "Integration", "Medium",
     "Caller sends X-API-Key",
     "1. GET /workspace with X-API-Key header",
     "valid key",
     "200 OK; principal is ApiKey", "PROPOSED",
     "PROPOSED", "n/a", "/**",
     "Logic present"),
    ("TC-CROSS-003", "US-CROSS-003", "AC-CROSS-003", "FC-CROSS-003", "Cross-cutting",
     "Read goes to slave", "Integration", "Medium",
     "@ReadOnly annotated method",
     "1. Enable SQL log 2. Call GET /workspace",
     "n/a",
     "SELECT against slave datasource", "PROPOSED",
     "PROPOSED", "n/a", "/workspace",
     "Configuration present; manual verification only"),
    ("TC-CROSS-004", "US-CROSS-004", "AC-CROSS-004", "FC-CROSS-004", "Cross-cutting",
     "Email only after commit", "Integration", "Medium",
     "Invitation commit succeeds",
     "1. POST /workspace/{id}/invitations 2. Observe SMTP",
     "valid invite",
     "Email sent only after commit", "PROPOSED",
     "PROPOSED", "n/a", "/workspace/{id}/invitations",
     "Logic present"),
]

# ===== Summary =====
summary_rows = [
    ("Total modules", 12),
    ("Total US", len(user_stories)),
    ("Total AC", len(acceptance_criteria)),
    ("Total FC", len(functional_requirements)),
    ("Total NFC", len(non_functional)),
    ("Total Test Cases", len(test_cases)),
]
evidence_count = {"EXPLICIT": 0, "INFERRED": 0, "NEEDS_REVIEW": 0}
for r in user_stories:
    evidence_count[r[7]] = evidence_count.get(r[7], 0) + 1
for r in functional_requirements:
    evidence_count[r[11]] = evidence_count.get(r[11], 0) + 1
for r in non_functional:
    evidence_count[r[6]] = evidence_count.get(r[6], 0) + 1
for r in test_cases:
    evidence_count[r[13]] = evidence_count.get(r[13], 0) + 1
summary_rows.append(("EXPLICIT count (across US/FC/NFC/TC)", evidence_count["EXPLICIT"]))
summary_rows.append(("INFERRED count (across US/FC/NFC/TC)", evidence_count["INFERRED"]))
summary_rows.append(("NEEDS_REVIEW count (across US/FC/NFC/TC)", evidence_count["NEEDS_REVIEW"]))


# ===== Build workbook =====
wb = Workbook()
ws = wb.active
wb.remove(ws)

# ---- Sheet: User_Stories ----
ws_us = wb.create_sheet("User_Stories")
headers = ["US_ID", "Module", "Actor", "User_Story", "Business_Value", "Priority", "Status",
           "Evidence_Type", "Source_File", "Source_Symbol", "Notes"]
rows = [list(r) for r in user_stories]
write_table(ws_us, headers, rows, widths={1:14,2:16,3:18,4:80,5:45,6:10,7:13,8:14,9:55,10:32,11:55})
add_dropdowns(ws_us, "F", ["High", "Medium", "Low"], ws_us.max_row)
add_dropdowns(ws_us, "G", ["Implemented", "Proposed", "Deprecated"], ws_us.max_row)
add_dropdowns(ws_us, "H", ["EXPLICIT", "INFERRED", "NEEDS_REVIEW"], ws_us.max_row)

# ---- Sheet: Acceptance_Criteria ----
ws_ac = wb.create_sheet("Acceptance_Criteria")
headers = ["AC_ID", "US_ID", "Scenario", "Given", "When", "Then", "Business_Rule",
           "Evidence_Type", "Source_File", "Source_Symbol"]
rows = []
ac_rules = {
    "AC-AUTH-008": "All non-public endpoints require JWT",
    "AC-AUTH-009": "Valid JWT authorizes request",
    "AC-INVITE-002": "Cannot invite yourself",
    "AC-INVITE-003": "Inviter cannot assign ADMIN role",
    "AC-INVITE-007": "Expired invitations cannot be accepted",
    "AC-RBAC-002": "ADMIN role must keep WORKSPACE_ADMINISTER",
    "AC-RBAC-003": "Cannot demote last admin",
    "AC-SPRINT-003": "Story must belong to same workspace",
    "AC-SPRINT-006": "Only one active sprint per workspace",
    "AC-US-004": "Story status can change only inside active sprint",
    "AC-US-005": "Story status can change only inside active sprint",
}
for ac in acceptance_criteria:
    rows.append([ac[0], ac[1], ac[2], ac[3], ac[4], ac[5], ac_rules.get(ac[0], ""), "EXPLICIT",
                 "see Source_File of parent US", "see Source_Symbol of parent US"])
write_table(ws_ac, headers, rows, widths={1:14,2:14,3:30,4:55,5:55,6:55,7:45,8:14,9:35,10:35})

# ---- Sheet: Functional_Requirements ----
ws_fc = wb.create_sheet("Functional_Requirements")
headers = ["FC_ID", "US_ID", "Module", "Requirement", "Input", "Processing", "Output",
           "Role_Permission", "API_Endpoint", "HTTP_Method", "Evidence_Type",
           "Source_File", "Source_Symbol"]
rows = [list(r) for r in functional_requirements]
write_table(ws_fc, headers, rows, widths={1:18,2:14,3:18,4:55,5:35,6:55,7:35,8:22,9:55,10:18,11:14,12:55,13:32})
add_dropdowns(ws_fc, "J", ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "ANY", "INTERNAL", "N/A"], ws_fc.max_row)
add_dropdowns(ws_fc, "K", ["EXPLICIT", "INFERRED", "NEEDS_REVIEW"], ws_fc.max_row)

# ---- Sheet: Non_Functional_Requirements ----
ws_nfc = wb.create_sheet("Non_Functional_Requirements")
headers = ["NFC_ID", "Category", "Requirement", "Metric_Or_Constraint", "Current_Implementation",
           "Verification_Method", "Evidence_Type", "Source_File", "Source_Symbol", "Notes"]
rows = [list(r) for r in non_functional]
write_table(ws_nfc, headers, rows, widths={1:22,2:18,3:55,4:45,5:55,6:45,7:14,8:55,9:35,10:55})
add_dropdowns(ws_nfc, "B", ["Security", "Performance", "Reliability", "Availability",
                             "Scalability", "Maintainability", "Observability",
                             "Data integrity", "Compatibility", "Usability"], ws_nfc.max_row)
add_dropdowns(ws_nfc, "G", ["EXPLICIT", "INFERRED", "NEEDS_REVIEW"], ws_nfc.max_row)

# ---- Sheet: Test_Cases ----
ws_tc = wb.create_sheet("Test_Cases")
headers = ["TC_ID", "US_ID", "AC_ID", "FC_ID", "Module", "Test_Case_Name", "Test_Type",
           "Priority", "Preconditions", "Test_Steps", "Test_Data", "Expected_Result",
           "Actual_Result", "Status", "Automation_Status", "Source_Test_File",
           "Related_API", "Notes"]
rows = [list(r) for r in test_cases]
write_table(ws_tc, headers, rows, widths={1:14,2:14,3:14,4:18,5:18,6:38,7:18,8:10,9:45,10:65,11:35,12:45,13:18,14:12,15:18,16:50,17:35,18:45})
add_dropdowns(ws_tc, "G", ["Unit", "Integration", "E2E (Playwright)", "Configuration", "Unit + Integration"], ws_tc.max_row)
add_dropdowns(ws_tc, "H", ["High", "Medium", "Low"], ws_tc.max_row)
add_dropdowns(ws_tc, "N", ["PASS", "FAIL", "BLOCKED", "SKIPPED", "PROPOSED"], ws_tc.max_row)
add_dropdowns(ws_tc, "O", ["AUTOMATED", "PROPOSED", "MANUAL"], ws_tc.max_row)

# ---- Sheet: Traceability_Matrix ----
ws_tx = wb.create_sheet("Traceability_Matrix")
headers = ["Module", "US_ID", "AC_ID", "FC_ID", "NFC_ID", "TC_ID",
           "Implementation_File", "Test_File", "Coverage_Status", "Review_Note"]
tx_rows = []
# Build map from US->AC->FC->TC and a default NFC_PER_MODULE (we just use the matching NFC by category)
# We'll generate one row per US with associated FC and a couple of TC ids, plus a representative NFC id.
nfc_by_module = {
    "Authentication": "NFC-SECURITY-001",
    "Profile": "NFC-SECURITY-001",
    "Workspace": "NFC-SECURITY-002",
    "Workspace Member": "NFC-SECURITY-002",
    "Invitation": "NFC-SECURITY-006",
    "RBAC": "NFC-SECURITY-002",
    "Sprint": "NFC-RELIABILITY-001",
    "User Story": "NFC-DATA-INTEGRITY-001",
    "Notification": "NFC-RELIABILITY-003",
    "Graph": "NFC-SCALABILITY-001",
    "Observability": "NFC-OBSERVABILITY-001",
    "Cross-cutting": "NFC-SCALABILITY-002",
}
# Index helpers
us_index = {u[0]: u for u in user_stories}
fc_by_us = {}
for fc in functional_requirements:
    fc_by_us.setdefault(fc[1], []).append(fc[0])
ac_by_us = {}
for ac in acceptance_criteria:
    ac_by_us.setdefault(ac[1], []).append(ac[0])
tc_by_us = {}
for tc in test_cases:
    tc_by_us.setdefault(tc[1], []).append(tc[0])

for us in user_stories:
    us_id, module = us[0], us[1]
    fc_id = fc_by_us.get(us_id, [""])[0]
    ac_id = ac_by_us.get(us_id, [""])[0]
    tc_ids = tc_by_us.get(us_id, [])
    tc_id = tc_ids[0] if tc_ids else ""
    nfc_id = nfc_by_module.get(module, "NFC-MAINTAINABILITY-001")
    test_files = []
    impl_files = [us[8]]
    for t in test_cases:
        if t[1] == us_id:
            if t[15] != "n/a":
                test_files.append(t[15])
    status = "COVERED" if any(t[1] == us_id and t[13] == "PASS" for t in test_cases) else (
        "PARTIAL" if any(t[1] == us_id and t[13] == "PROPOSED" for t in test_cases) else "MISSING"
    )
    note = ""
    if status == "MISSING":
        note = "No automated test; logic confirmed in code only"
    elif status == "PARTIAL":
        note = "Test proposed; needs to be implemented"
    tx_rows.append([module, us_id, ac_id, fc_id, nfc_id, tc_id,
                    "; ".join(impl_files), "; ".join(test_files) or "n/a", status, note])

write_table(ws_tx, headers, tx_rows, widths={1:18,2:14,3:14,4:18,5:22,6:18,7:55,8:55,9:16,10:55})
add_dropdowns(ws_tx, "I", ["COVERED", "PARTIAL", "MISSING", "BLOCKED"], ws_tx.max_row)

# ---- Sheet: Summary ----
ws_sum = wb.create_sheet("Summary")
ws_sum.append(["Metric", "Value"])
style_header(ws_sum, 2)
module_counts = {}
for u in user_stories:
    module_counts[u[1]] = module_counts.get(u[1], 0) + 1
rows = [
    ["Total modules", len(module_counts)],
    ["Total US", len(user_stories)],
    ["Total AC", len(acceptance_criteria)],
    ["Total FC", len(functional_requirements)],
    ["Total NFC", len(non_functional)],
    ["Total Test Cases", len(test_cases)],
    ["EXPLICIT (US+FC+NFC+TC)", evidence_count["EXPLICIT"]],
    ["INFERRED (US+FC+NFC+TC)", evidence_count["INFERRED"]],
    ["NEEDS_REVIEW (US+FC+NFC+TC)", evidence_count["NEEDS_REVIEW"]],
]
for k, v in module_counts.items():
    rows.append([f"US in {k}", v])

missing_tests = []
for u in user_stories:
    has_test = any(t[1] == u[0] and t[13] in ("PASS", "PROPOSED") for t in test_cases)
    if not has_test:
        missing_tests.append(u[0])
rows.append(["US without test case (count)", len(missing_tests)])
for mt in missing_tests:
    rows.append([f" - {mt}", "MISSING"])

# Risks / gaps detected
risks = [
    "Performance SLA not defined anywhere in code (response time, throughput, availability)",
    "Most test cases are PROPOSED; only 2 backend unit tests + 6 Playwright E2E specs exist",
    "No integration tests for HTTP layer (controllers), GraphQL resolver, security filters",
    "WebSocket push notifications have no automated test",
    "Frontend has no unit tests (only Playwright E2E)",
    "ANALYZE_USER_STORIES Python module + 3.6 GB word2vec model not integrated into runtime",
    "frontend (Flutter) and frontend-mvvm (Flutter) folders appear unused - duplicate prototype",
    "Frontend Profile page is mocked (no backend integration)",
    "JWT refresh logic in api.ts uses single-flight pattern but is untested",
    "CORS configured as allowedOriginPatterns='*' - too permissive for production",
    "Default permissions hardcoded; RBAC matrix not data-driven",
]
rows.append(["Risks / gaps (count)", len(risks)])
for r in risks:
    rows.append([f" - {r}", ""])

for r in rows:
    ws_sum.append(r)
for row in ws_sum.iter_rows(min_row=1, max_row=ws_sum.max_row, min_col=1, max_col=2):
    for c in row:
        c.border = BORDER
        c.alignment = WRAP
ws_sum.column_dimensions["A"].width = 60
ws_sum.column_dimensions["B"].width = 18

# Save
wb.save(OUTPUT_PATH)
print(f"Saved {OUTPUT_PATH}")
print(f"Modules: {len(module_counts)} | US: {len(user_stories)} | AC: {len(acceptance_criteria)} | "
      f"FC: {len(functional_requirements)} | NFC: {len(non_functional)} | TC: {len(test_cases)}")
